import letterManifest from '../../data/letter-audio-manifest.json'
import digraphManifest from '../../data/digraph-audio-manifest.json'
import nativeWordManifest from '../../data/word-audio-manifest.json'
import fallbackData from '../../data/word-grapheme-fallbacks.json'
import { getKnowledgeNode } from '../../data/knowledge/registry'
import { POLISH_DIGRAPH_IDS, wordToAudioGraphemeIds } from '../graphemes'

const BASE = import.meta.env.BASE_URL

const MANIFESTS: Record<string, Record<string, string>> = {
  alphabet: letterManifest,
  digraphs: digraphManifest,
}

/**
 * Grapheme-spelling fallbacks when no native clip exists.
 * Generated by scripts/generate-word-grapheme-fallbacks.py — do not hand-edit.
 * Native word-audio-manifest.json always wins if both exist.
 */
const GRAPHENE_FALLBACKS: Record<string, string[]> = fallbackData.fallbacks

let currentAudio: HTMLAudioElement | null = null
let sequenceAbort: (() => void) | null = null

export type WordAudioSource = 'native' | 'grapheme-fallback'

export function hasUnitRecording(moduleId: string, unitId: string): boolean {
  return Boolean(MANIFESTS[moduleId]?.[unitId])
}

export function isModuleAudioAvailable(moduleId: string): boolean {
  const manifest = MANIFESTS[moduleId]
  if (!manifest) return false
  const expected = moduleId === 'alphabet' ? 32 : moduleId === 'digraphs' ? 7 : 0
  return Object.keys(manifest).length >= expected
}

function audioUrl(moduleId: string, unitId: string): string | null {
  const rel = MANIFESTS[moduleId]?.[unitId]
  if (!rel) return null
  return `${BASE}${rel}`
}

function stopCurrentClip(): void {
  if (currentAudio) {
    currentAudio.pause()
    currentAudio.currentTime = 0
    currentAudio = null
  }
}

export function stopUnitAudio(): void {
  sequenceAbort?.()
  sequenceAbort = null
  stopCurrentClip()
}

/** @deprecated use stopUnitAudio */
export const stopLetterAudio = stopUnitAudio

export function playUnitAudio(
  moduleId: string,
  unitId: string,
  options?: {
    onEnd?: () => void
    onError?: () => void
    /** When false, only stops the current clip — keeps an active grapheme sequence alive */
    interrupt?: boolean
  },
): boolean {
  const url = audioUrl(moduleId, unitId)
  if (!url) {
    options?.onError?.()
    return false
  }

  if (options?.interrupt !== false) {
    stopUnitAudio()
  } else {
    stopCurrentClip()
  }

  const audio = new Audio(url)
  currentAudio = audio
  audio.onended = () => {
    if (currentAudio === audio) currentAudio = null
    options?.onEnd?.()
  }
  audio.onerror = () => {
    if (currentAudio === audio) currentAudio = null
    options?.onError?.()
  }
  void audio.play().catch(() => options?.onError?.())
  return true
}

export function hasNativeWordRecording(wordId: string): boolean {
  return Boolean(nativeWordManifest[wordId as keyof typeof nativeWordManifest])
}

export function hasGraphemeFallbackWord(wordId: string): boolean {
  if (hasNativeWordRecording(wordId)) return false
  return Boolean(getGraphemeFallbackSequence(wordId)?.length)
}

export function getGraphemeFallbackSequence(wordId: string): string[] | null {
  if (hasNativeWordRecording(wordId)) return null
  const stored = GRAPHENE_FALLBACKS[wordId]
  if (stored?.length) return stored
  const node = getKnowledgeNode(wordId)
  if (node) return buildAudioGraphemeSequence(node.label)
  return null
}

/** Build a playable grapheme sequence for a surface form (letters + digraphs with recordings). */
export function buildAudioGraphemeSequence(surface: string): string[] | null {
  const ids = wordToAudioGraphemeIds(surface)
  if (!ids.length) return null
  for (const g of ids) {
    const moduleId = (POLISH_DIGRAPH_IDS as Set<string>).has(g) ? 'digraphs' : 'alphabet'
    if (!hasUnitRecording(moduleId, g)) return null
  }
  return ids
}

/** True only for native recordings — required for audio-based exercises. */
export function hasWordRecording(wordId: string): boolean {
  return hasNativeWordRecording(wordId)
}

export function getWordAudioSource(wordId: string): WordAudioSource | null {
  if (hasNativeWordRecording(wordId)) return 'native'
  if (hasGraphemeFallbackWord(wordId)) return 'grapheme-fallback'
  return null
}

export function hasWordPlayback(wordId: string): boolean {
  return getWordAudioSource(wordId) !== null
}

export function isVocabHearFormat(format: string): boolean {
  return format === 'vocab-hear-pick-meaning' || format === 'vocab-hear-pick-word'
}

export function wordAudioSourceLabel(source: WordAudioSource | null): string | null {
  if (source === 'grapheme-fallback') return 'Letter sounds'
  return null
}

function nativeWordAudioUrl(wordId: string): string | null {
  const rel = nativeWordManifest[wordId as keyof typeof nativeWordManifest]
  if (!rel) return null
  return `${BASE}${rel}`
}

export function playWordAudio(
  wordId: string,
  options?: { onEnd?: () => void; onError?: () => void },
): boolean {
  const url = nativeWordAudioUrl(wordId)
  if (url) {
    stopUnitAudio()
    const audio = new Audio(url)
    currentAudio = audio
    audio.onended = () => {
      if (currentAudio === audio) currentAudio = null
      options?.onEnd?.()
    }
    audio.onerror = () => {
      if (currentAudio === audio) currentAudio = null
      options?.onError?.()
    }
    void audio.play().catch(() => options?.onError?.())
    return true
  }

  const sequence = getGraphemeFallbackSequence(wordId)
  if (!sequence?.length) {
    options?.onError?.()
    return false
  }

  const gapMs = sequence.length > 12 ? 220 : 300
  stopUnitAudio()
  sequenceAbort = playGraphemeSequence(sequence, {
    gapMs,
    onEnd: () => {
      sequenceAbort = null
      options?.onEnd?.()
    },
    onError: () => {
      sequenceAbort = null
      options?.onError?.()
    },
  })
  return true
}

/** Play graphemes one after another; returns abort function */
export function playGraphemeSequence(
  graphemes: string[],
  options?: {
    gapMs?: number
    onStep?: (index: number) => void
    onEnd?: () => void
    onError?: () => void
  },
): () => void {
  const gapMs = options?.gapMs ?? 350
  let cancelled = false
  let index = 0

  const abort = () => {
    cancelled = true
    stopCurrentClip()
  }

  const playNext = () => {
    if (cancelled) return
    if (index >= graphemes.length) {
      options?.onEnd?.()
      return
    }
    const g = graphemes[index]
    const step = index
    index++
    options?.onStep?.(step)
    const moduleId = (POLISH_DIGRAPH_IDS as Set<string>).has(g) ? 'digraphs' : 'alphabet'
    const ok = playUnitAudio(moduleId, g, {
      interrupt: false,
      onEnd: () => {
        if (cancelled) return
        setTimeout(playNext, gapMs)
      },
      onError: () => options?.onError?.(),
    })
    if (!ok) options?.onError?.()
  }

  playNext()
  return abort
}

/** @deprecated use playUnitAudio */
export function playLetterAudio(
  letterId: string,
  options?: { onEnd?: () => void; onError?: () => void },
): boolean {
  return playUnitAudio('alphabet', letterId, options)
}

/** @deprecated */
export function hasLetterRecording(letterId: string): boolean {
  return hasUnitRecording('alphabet', letterId)
}

/** @deprecated */
export function isLetterAudioAvailable(): boolean {
  return isModuleAudioAvailable('alphabet')
}

export const LETTER_AUDIO_ATTRIBUTION = {
  title: 'Polish Alphabet.oga',
  author: 'Wyksztalcioch',
  license: 'Public domain',
  url: 'https://commons.wikimedia.org/wiki/File:Polish_Alphabet.oga',
}

export const DIGRAPH_AUDIO_ATTRIBUTION = {
  title: 'Wikimedia Commons pronunciation clips',
  author: 'Various native speakers',
  license: 'See individual files on Wikimedia Commons',
  url: 'https://commons.wikimedia.org/wiki/Category:Polish_pronunciation',
}
