#!/usr/bin/env python3
"""Build word-grapheme-fallbacks.json for words without native recordings.

Native entries in word-audio-manifest.json always take precedence at runtime.
This file only lists words that can be spelled from letter/digraph clips.

Run: python3 scripts/generate-word-grapheme-fallbacks.py
"""
from __future__ import annotations

import json
import re
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "src" / "data" / "word-audio-manifest.json"
LETTER_MANIFEST = ROOT / "src" / "data" / "letter-audio-manifest.json"
DIGRAPH_MANIFEST = ROOT / "src" / "data" / "digraph-audio-manifest.json"
VOCAB = ROOT / "src" / "data" / "knowledge" / "vocabulary.ts"
OUT = ROOT / "src" / "data" / "word-grapheme-fallbacks.json"

MULTIGRAPHS = ["dź", "dż", "dz", "ch", "cz", "rz", "sz"]
DIGRAPH_IDS = set(MULTIGRAPHS)
LETTER_OK = re.compile(r"[a-ząćęłńóśźż]$")

SPELLING_TO_PHONEME = {
    "dzi": "dź",
    "ci": "ć",
    "si": "ś",
    "zi": "ź",
    "ni": "ń",
}


def slug(word: str) -> str:
    s = unicodedata.normalize("NFD", word.lower())
    s = "".join(c for c in s if unicodedata.category(c) != "Mn")
    return s.replace("ł", "l")


def highlight_to_unit(h: str) -> str:
    return SPELLING_TO_PHONEME.get(h, h)


def tokenize_graphemes(word: str) -> list[str]:
    lower = word.lower()
    tokens: list[str] = []
    i = 0
    while i < len(lower):
        matched = None
        for mg in MULTIGRAPHS:
            if lower[i : i + len(mg)] == mg:
                matched = mg
                i += len(mg)
                break
        if not matched:
            tokens.append(lower[i])
            i += 1
        else:
            tokens.append(matched)
    return tokens


def graphemes_to_audio_ids(graphemes: list[str]) -> list[str]:
    out: list[str] = []
    i = 0
    while i < len(graphemes):
        triple = graphemes[i] + (graphemes[i + 1] if i + 1 < len(graphemes) else "") + (
            graphemes[i + 2] if i + 2 < len(graphemes) else ""
        )
        pair = graphemes[i] + (graphemes[i + 1] if i + 1 < len(graphemes) else "")
        if triple in SPELLING_TO_PHONEME:
            out.append(SPELLING_TO_PHONEME[triple])
            i += 3
        elif pair in SPELLING_TO_PHONEME:
            out.append(SPELLING_TO_PHONEME[pair])
            i += 2
        else:
            out.append(highlight_to_unit(graphemes[i]))
            i += 1
    return out


def word_to_audio_grapheme_ids(word: str) -> list[str]:
    sequence: list[str] = []
    for part in word.strip().split():
        clean = re.sub(r"[^\wąćęłńóśźż]", "", part, flags=re.IGNORECASE)
        if not clean:
            continue
        sequence.extend(graphemes_to_audio_ids(tokenize_graphemes(clean)))
    return sequence


MAX_COMPOSABLE = 6


def is_composable_word_audio(surface: str, audio_ids: list[str]) -> bool:
    if not audio_ids or len(audio_ids) > MAX_COMPOSABLE:
        return False
    if re.search(r"\s", surface.strip()):
        return False
    clean = re.sub(r"[^\wąćęłńóśźż]", "", surface, flags=re.IGNORECASE)
    if not clean:
        return False
    expected = word_to_audio_grapheme_ids(clean)
    return len(expected) == len(audio_ids) and all(a == b for a, b in zip(expected, audio_ids))


def playable_graphemes(word: str, letters: set[str], digraphs: set[str]) -> list[str] | None:
    sequence = word_to_audio_grapheme_ids(word)
    for g in sequence:
        if g in DIGRAPH_IDS:
            if g not in digraphs:
                return None
        elif not LETTER_OK.match(g):
            return None
        elif g not in letters:
            return None
    if not is_composable_word_audio(word, sequence):
        return None
    return sequence if sequence else None


def load_vocabulary() -> list[tuple[str, str]]:
    """Parse VOCABULARY from knowledge/vocabulary.ts."""
    src = VOCAB.read_text()
    words: list[tuple[str, str]] = []
    pattern = re.compile(
        r"(?:w|phrase)\(\s*'((?:\\'|[^'])*)'\s*,\s*(?:'((?:\\'|[^'])*)'|\"((?:\\\"|[^\"])*)\")",
    )
    for m in pattern.finditer(src):
        word = m.group(1).replace("\\'", "'")
        words.append((slug(word), word))
    return words


def main() -> None:
    native = set(json.loads(MANIFEST.read_text()).keys())
    letters = set(json.loads(LETTER_MANIFEST.read_text()).keys())
    digraphs = set(json.loads(DIGRAPH_MANIFEST.read_text()).keys())

    fallbacks: dict[str, list[str]] = {}
    skipped: list[str] = []

    for word_id, surface in load_vocabulary():
        if word_id in native:
            continue
        seq = playable_graphemes(surface, letters, digraphs)
        if seq:
            fallbacks[word_id] = seq
        else:
            skipped.append(surface)

    OUT.write_text(
        json.dumps(
            {
                "_comment": "Grapheme-spelling fallbacks when no native word audio exists. "
                "Native word-audio-manifest.json always wins. Generated by scripts/generate-word-grapheme-fallbacks.py",
                "fallbacks": fallbacks,
            },
            ensure_ascii=False,
            indent=2,
        )
        + "\n",
    )
    print(f"{len(fallbacks)} grapheme fallbacks, {len(skipped)} without audio:")
    for w in skipped[:20]:
        print(f"  - {w}")
    if len(skipped) > 20:
        print(f"  ... and {len(skipped) - 20} more")


if __name__ == "__main__":
    main()
