#!/usr/bin/env python3
"""Build word-grapheme-fallbacks.json for words without native recordings.

Native entries in word-audio-manifest.json always take precedence at runtime.
This file only lists words that can be spelled from letter/digraph clips.

Run: python3 scripts/generate-word-grapheme-fallbacks.py
"""
from __future__ import annotations

import json
import re
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "src" / "data" / "word-audio-manifest.json"
LETTER_MANIFEST = ROOT / "src" / "data" / "letter-audio-manifest.json"
DIGRAPH_MANIFEST = ROOT / "src" / "data" / "digraph-audio-manifest.json"
OUT = ROOT / "src" / "data" / "word-grapheme-fallbacks.json"

MULTIGRAPHS = ["dź", "dż", "dz", "ch", "cz", "rz", "sz"]
DIGRAPH_IDS = set(MULTIGRAPHS)
LETTER_OK = re.compile(r"[a-ząćęłńóśźż]$")


def slug(word: str) -> str:
    s = unicodedata.normalize("NFD", word.lower())
    s = "".join(c for c in s if unicodedata.category(c) != "Mn")
    return s.replace("ł", "l")


def tokenize_graphemes(word: str) -> list[str]:
    lower = word.lower()
    tokens: list[str] = []
    i = 0
    while i < len(lower):
        matched = None
        for mg in MULTIGRAPHS:
            if lower[i : i + len(mg)] == mg:
                matched = mg
                i += len(mg)
                break
        if not matched:
            tokens.append(lower[i])
            i += 1
        else:
            tokens.append(matched)
    return tokens


def playable_graphemes(word: str, letters: set[str], digraphs: set[str]) -> list[str] | None:
    sequence: list[str] = []
    for part in word.strip().split():
        for g in tokenize_graphemes(part):
            if g in DIGRAPH_IDS:
                if g not in digraphs:
                    return None
            elif not LETTER_OK.match(g):
                continue
            elif g not in letters:
                return None
            sequence.append(g)
    return sequence if sequence else None


def load_basic_words() -> list[tuple[str, str]]:
    """Parse BASIC_WORDS from basicWords.ts without importing TS."""
    src = (ROOT / "src" / "data" / "basicWords.ts").read_text()
    words: list[tuple[str, str]] = []
    pattern = re.compile(
        r"bw\(\s*'((?:\\'|[^'])*)'\s*,\s*(?:'((?:\\'|[^'])*)'|\"((?:\\\"|[^\"])*)\")",
    )
    for m in pattern.finditer(src):
        word = m.group(1).replace("\\'", "'")
        words.append((slug(word), word))
    return words


def main() -> None:
    native = set(json.loads(MANIFEST.read_text()).keys())
    letters = set(json.loads(LETTER_MANIFEST.read_text()).keys())
    digraphs = set(json.loads(DIGRAPH_MANIFEST.read_text()).keys())

    fallbacks: dict[str, list[str]] = {}
    skipped: list[str] = []

    for word_id, surface in load_basic_words():
        if word_id in native:
            continue
        seq = playable_graphemes(surface, letters, digraphs)
        if seq:
            fallbacks[word_id] = seq
        else:
            skipped.append(surface)

    OUT.write_text(
        json.dumps(
            {
                "_comment": "Grapheme-spelling fallbacks when no native word audio exists. "
                "Native word-audio-manifest.json always wins. Generated by scripts/generate-word-grapheme-fallbacks.py",
                "fallbacks": fallbacks,
            },
            ensure_ascii=False,
            indent=2,
        )
        + "\n",
    )
    print(f"{len(fallbacks)} grapheme fallbacks, {len(skipped)} without audio:")
    for w in skipped[:20]:
        print(f"  - {w}")
    if len(skipped) > 20:
        print(f"  ... and {len(skipped) - 20} more")


if __name__ == "__main__":
    main()
